<?php
return [
    'field' => [
        'text' => 'text',
        'integer' => 'integer',
        'decimal' => 'decimal',
        'boolean' => 'boolean',
        'date' => 'date',
        'datetime' => 'datetime',
        'time' => 'time',
        'month' => 'month',
        'select' => 'select',
        'textarea' => 'textarea',
        'reference' => 'reference',
        'search_popup' => 'search_popup',
        'primaryKey' => 'primaryKey',
        'password' => 'password',
        'image' => 'image',
        'view' => 'view',
        'view_search_popup' => 'view_search_popup',
        'view_select' => 'view_select',
        'view_boolean' => 'view_boolean',
        'view_image' => 'view_image',
        'tiny_mce' => 'tiny_mce',
        'multiple_image' => 'multiple_image',
    ],
    'explode_filter' => '_:',
    'news_category' => [
        'movies' => 1,
        'sports' => 2,
        'technology' => 3,
        'lifestyle' => 4,
        'trending' => 5,
        'magazine' => 6,
        'india' => 7,
        'television' => 8,
        'business' => 9,
        'science' => 10,
        'education' => 11,
        'cities' => 12,
        'auto' => 13,
        'world' => 14,
        'others' => 15,
    ]
];
