<?php
return [
    'field' => [
        'text' => 'text',
        'integer' => 'integer',
        'decimal' => 'decimal',
        'boolean' => 'boolean',
        'date' => 'date',
        'datetime' => 'datetime',
        'time' => 'time',
        'month' => 'month',
        'select' => 'select',
        'textarea' => 'textarea',
        'reference' => 'reference',
        'search_popup' => 'search_popup',
        'primaryKey' => 'primaryKey',
        'password' => 'password',
        'image' => 'image',
        'view' => 'view',
        'view_search_popup' => 'view_search_popup',
        'view_select' => 'view_select',
        'view_boolean' => 'view_boolean',
        'view_image' => 'view_image',
        'tiny_mce' => 'tiny_mce',
        'multiple_image' => 'multiple_image',
    ],
    'explode_filter' => '_:',
    'home_positions' => [
        'Position 1',
        'Position 2',
        'Position 3',
        'Position 4',
        'Position 5',
    ]
];
